# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ditto < Formula
  desc "Real production data, PII scrubbed, isolated for every run — ephemeral Postgres and MySQL copies, no shared state."
  homepage "https://github.com/attaradev/ditto"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/attaradev/ditto/releases/download/v0.1.0/ditto_0.1.0_darwin_amd64.tar.gz"
      sha256 "483043210560ef28e7d0ece916107040402b82f05fbe9115f8a157243ffa5c3b"

      define_method(:install) do
        bin.install "ditto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/attaradev/ditto/releases/download/v0.1.0/ditto_0.1.0_darwin_arm64.tar.gz"
      sha256 "96d70a930a38961d3699a2753866b352d289336b04a62c208f3eb0677d238305"

      define_method(:install) do
        bin.install "ditto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/attaradev/ditto/releases/download/v0.1.0/ditto_0.1.0_linux_amd64.tar.gz"
      sha256 "2f107013f9af542a1898337d21e7557f2703c71e0e81fc952ce4c492e4bbc6a5"
      define_method(:install) do
        bin.install "ditto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/attaradev/ditto/releases/download/v0.1.0/ditto_0.1.0_linux_arm64.tar.gz"
      sha256 "1dea89ebec7ce23e0d2bcbcaaea76cd3d3ade069c6f55c4ccc33bb1ad0185993"
      define_method(:install) do
        bin.install "ditto"
      end
    end
  end

  test do
    system "#{bin}/ditto", "--version"
  end
end
