# This file was generated by GoReleaser. DO NOT EDIT.
cask "ditto" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "d0fb953aed2fb6dba79dca7db06d62a444a0fde31be81b62f9970df8d6c08ae5"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
    on_arm do
      sha256 "0f519c35b55987fd107c05b811434e3932f9a12246b49491ab0b47dbd3d00300"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
  end

  on_linux do
    on_intel do
      sha256 "d929327fb78a005d9569be804b3eaef7093c1cc29013abf87bd7bc79547e1f2d"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_linux_amd64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
    on_arm do
      sha256 "d8e6e38509662058437beaaae7a885c59191de947623c1c73979bbe4f6843004"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_linux_arm64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
  end

  name "ditto"
  desc "Real production data, PII scrubbed, isolated for every run — ephemeral Postgres and MySQL copies, no shared state."
  homepage "https://github.com/attaradev/ditto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ditto"

  # No zap stanza required

end
