# This file was generated by GoReleaser. DO NOT EDIT.
cask "ditto" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "cbb986c8c603c167be8542fd8b9e51ff0db6aca42630cc7ffe9c4619590a3e70"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
    on_arm do
      sha256 "f17b05c5ee79a8fcb99c705b3ed58bda06387f5104982fa36375f53a8f42a264"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
  end

  on_linux do
    on_intel do
      sha256 "f00a2abb026a0a19fedd02e1fcf613bff8cfec8f84b19d3c97f5172cf5e29148"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_linux_amd64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
    on_arm do
      sha256 "391982a8c10196d80541d56d5ab0ec04a50ab3d83b5f69d9f6e791449c3da9ea"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_linux_arm64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
  end

  name "ditto"
  desc "Real production data, PII scrubbed, isolated for every run — ephemeral Postgres and MySQL copies, no shared state."
  homepage "https://github.com/attaradev/ditto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ditto"

  # No zap stanza required

end
