# This file was generated by GoReleaser. DO NOT EDIT.
cask "ditto" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c8708bec1b5a5ecf29e6e0b6bebb46b0389804a563486f5c457092d6c40eb5ae"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
    on_arm do
      sha256 "b23fa687b4519ebb4755d09db57076d62fc2891944839a2174e1c2197b0d2cda"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
  end

  on_linux do
    on_intel do
      sha256 "b022d5329a924f7102591857d8efd949a782d597d87cb47e852b6e99d7bffdfd"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_linux_amd64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
    on_arm do
      sha256 "08f0c1996fcc0116209571a4a37abab7a75457dd925128439833acceca40691e"
      url "https://github.com/attaradev/ditto/releases/download/v#{version}/ditto_#{version}_linux_arm64.tar.gz",
        verified: "github.com/attaradev/ditto"
    end
  end

  name "ditto"
  desc "Real production data, PII scrubbed, isolated for every run — ephemeral Postgres and MySQL copies, no shared state."
  homepage "https://github.com/attaradev/ditto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ditto"

  # No zap stanza required

end
